
package interfaces;

import Conectores.Conexion;
import Conectores.DocumentoServicios;
import Conectores.EstudianteServicios;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelos.Documento;
import modelos.Estudiante;

public class Principal extends javax.swing.JFrame {
    
    Conexion cx;
    EstudianteServicios estudianteServicio;
    DocumentoServicios DocServ;
    Estudiante estudiante;
    Documento doc;
    public Principal() {
        initComponents();
        this.setTitle("PRINCIPAL");
        this.setSize(770,560);
        this.setLocationRelativeTo(null);
        //setSize( (int) this.getWidth(), (int) this.getHeight());
        //setLocation( (int) this.getWidth() - getWidth(), 0 );
        setResizable(false);
        cx = new Conexion();
        estudianteServicio = new EstudianteServicios();
        DocServ = new DocumentoServicios();
        
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        cboCivil = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        cboEstado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbCedula = new javax.swing.JCheckBox();
        cbTitulo = new javax.swing.JCheckBox();
        cbFondo = new javax.swing.JCheckBox();
        cbNotas = new javax.swing.JCheckBox();
        cbCarta = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo de estudiante");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 68, 132, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 132, -1, -1));

        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 20));

        jLabel4.setText("Buscar Estudiante");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 31, 141, -1));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 65, 105, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 65, 70, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 800, 10));

        jLabel5.setText("Cedula");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, 20));

        jLabel6.setText("Sexo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 40, 20));

        jLabel7.setText("Estado Civil");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 20));

        jLabel8.setText("Estado");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, 20));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 100, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 100, -1));
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 100, -1));
        getContentPane().add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 100, -1));

        cboCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Soltero", "Casado", "Viudo", "Divorciado" }));
        getContentPane().add(cboCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 100, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, -1, -1));

        btnReporte.setText("Reporteria");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Amazonas", "Anzoátegui", "Apure", "Aragua", "Barinas", "Bolívar", "Carabobo", "Cojedes", "Delta Amacuro", "Dependencias Federales", "Distrito Federal", "Falcón", "Guárico", "Lara", "Mérida", "Miranda", "Monagas", "Nueva Esparta", "Portuguesa", "Sucre", "Táchira", "Trujillo", "Vargas", "Yaracuy", "Zulia" }));
        getContentPane().add(cboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 100, -1));

        jLabel9.setText("Documentos cargados");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        cbCedula.setText("Cedula");
        getContentPane().add(cbCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        cbTitulo.setText("Titulo Bachiller");
        getContentPane().add(cbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        cbFondo.setText("Fondo negro");
        getContentPane().add(cbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        cbNotas.setText("Notas Bachiller");
        getContentPane().add(cbNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        cbCarta.setText("Carta Opsu");
        getContentPane().add(cbCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try {
            if(txtNombre.getText() != null && txtNombre.getText().length()>0 && 
            txtApellido.getText() != null && txtApellido.getText().length()>0 &&
            txtSexo.getText() != null && txtSexo.getText().length()>0 &&
            txtCedula.getText() != null && txtCedula.getText().length()>0 &&
            cboCivil.getSelectedIndex()!=0 &&
            cboEstado.getSelectedIndex()!=0       
            ) {
                
                Random r1 = new Random();
                int n = (int)(r1.nextDouble()*5000);
                doc = new Documento();
                doc.setId_documento(n);//codigo del registro de documento
                doc.setHayCar(cbCarta.isSelected());
                doc.setHayCed(cbCedula.isSelected());
                doc.setHayFon(cbFondo.isSelected());
                doc.setHayNot(cbNotas.isSelected());
                doc.setHayTit(cbTitulo.isSelected());
                
                estudiante = new Estudiante();
                estudiante.setNombre(txtNombre.getText());
                estudiante.setApellido(txtApellido.getText());
                estudiante.setSexo(txtSexo.getText());
                estudiante.setCedula(txtCedula.getText());
                estudiante.setIdEstado(cboEstado.getSelectedIndex());
                estudiante.setIdDoc(n);
                estudiante.setIdEdoCivil(cboCivil.getSelectedIndex());

                int confirmado = JOptionPane.showConfirmDialog(this, "¿Estas seguro?");
                if (JOptionPane.OK_OPTION == confirmado){
                    DocServ.guardar(cx.conectar(), doc);//documento guardado
                    estudianteServicio.guardar(cx.conectar(), estudiante);//guardado en la bd
                    JOptionPane.showMessageDialog(this, "¡Registro guardado exitosamente!");
                    limpio();
                }
            }else{
                JOptionPane.showMessageDialog(this, "¡Error, Complete todos los datos!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        if(txtBuscar.getText()!= null && txtBuscar.getText().length()>0){
            int id = Integer.parseInt(txtBuscar.getText());
            try {
                estudiante = estudianteServicio.recuperarPorId(cx.conectar(), id);
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
                btnGuardar.setEnabled(false);
                txtNombre.setText(estudiante.getNombre());
                txtApellido.setText(estudiante.getApellido());
                txtCedula.setText(estudiante.getCedula());
                txtSexo.setText(estudiante.getSexo());
                cboCivil.setSelectedIndex(estudiante.getIdEdoCivil());
                cboEstado.setSelectedIndex(estudiante.getIdEstado());
                doc = DocServ.recuperarPorId(cx.conectar(), estudiante.getIdDoc());
                cbCarta.setSelected(doc.isHayCar());
                cbCedula.setSelected(doc.isHayCed());
                cbFondo.setSelected(doc.isHayFon());
                cbTitulo.setSelected(doc.isHayTit());
                cbNotas.setSelected(doc.isHayNot());
                
            } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "¡Error, ingrese un ID a buscar!");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int prueba = cboEstado.getSelectedIndex();
        System.out.println(prueba);
        int confirmado = JOptionPane.showConfirmDialog(this, "¿Estas seguro?");
        if (JOptionPane.OK_OPTION == confirmado){
            try {
                estudianteServicio.eliminar(cx.conectar(), estudiante);//eliminar en la bd
                JOptionPane.showMessageDialog(this, "¡Registro borrado exitosamente!");
                limpio();
            } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        int confirmado = JOptionPane.showConfirmDialog(this, "¿Estas seguro?");
        if (JOptionPane.OK_OPTION == confirmado){
            try {
                estudiante.setNombre(txtNombre.getText());
                estudiante.setApellido(txtApellido.getText());
                estudiante.setSexo(txtSexo.getText());
                estudiante.setCedula(txtCedula.getText());
                estudiante.setIdEstado(cboEstado.getSelectedIndex());
                //estudiante.setIdDoc(3129);
                estudiante.setIdEdoCivil(cboCivil.getSelectedIndex());
                
                estudianteServicio.guardar(cx.conectar(), estudiante);//modificar en la bd
                doc.setId_documento(estudiante.getIdDoc());
                doc.setHayCar(cbCarta.isSelected());
                doc.setHayCed(cbCedula.isSelected());
                doc.setHayFon(cbFondo.isSelected());
                doc.setHayNot(cbNotas.isSelected());
                doc.setHayTit(cbTitulo.isSelected());
                DocServ.modificar(cx.conectar(), doc);//documento guardado
                
                JOptionPane.showMessageDialog(this, "¡Registro modificado exitosamente!");
                limpio();
            } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        this.setVisible(false);
        Reportes p = new Reportes();
        p.setVisible(true);
    }//GEN-LAST:event_btnReporteActionPerformed

    public void limpio(){
        txtNombre.setText("");
        txtApellido.setText("");
        txtSexo.setText("");
        txtCedula.setText("");
        txtBuscar.setText("");
        cboCivil.setSelectedIndex(0);
        cboEstado.setSelectedIndex(0);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(true);
        cbCarta.setSelected(false);
        cbCedula.setSelected(false);
        cbFondo.setSelected(false);
        cbNotas.setSelected(false);
        cbTitulo.setSelected(false);
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox cbCarta;
    private javax.swing.JCheckBox cbCedula;
    private javax.swing.JCheckBox cbFondo;
    private javax.swing.JCheckBox cbNotas;
    private javax.swing.JCheckBox cbTitulo;
    private javax.swing.JComboBox<String> cboCivil;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
